AllCops:
  TargetRubyVersion: 3.3
  UseCache: true

Metrics/MethodLength:
  Enabled: true
  Max: 15
Metrics/PerceivedComplexity:
  Max: 12
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/AbcSize:
  Max: 25

# Disable disrupting auto corrections, as I use rubocop as an ALE fixer.
Lint/RedundantRequireStatement:
  Enabled: true
  AutoCorrect: false
Lint/UselessAssignment:
  Enabled: true
  AutoCorrect: false
Lint/UnusedMethodArgument:
  Enabled: true
  AutoCorrect: false
Lint/UnusedBlockArgument:
  Enabled: true
  AutoCorrect: false
